# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dotnet-multienv

variables:
- group: aws

jobs:
- job: BuildModule2
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      mkdir ~/.aws
      echo [default] > ~/.aws/credentials
      echo aws_access_key_id=$(aws_access_key_id) >> ~/.aws/credentials
      echo aws_secret_access_key=$(aws_secret_access_key) >> ~/.aws/credentials
      
      echo [default] > ~/.aws/config
      echo region=ap-southeast-1 >> ~/.aws/config
      echo output=json >> ~/.aws/config
    displayName: 'Set AWS credential'

  # - script: |
  #     aws cloudformation create-stack --stack-name MythicalMysfitsCoreStack --capabilities CAPABILITY_NAMED_IAM --template-body file://module-2/cfn/core.yml   
  #   displayName: 'Create MythicalMysfitsCoreStack'

  - script: |
      cd ./module-2/webapi
      docker build . -t $(aws sts get-caller-identity --query Account --output text).dkr.ecr.$(aws configure get region).amazonaws.com/mythicalmysfits/service:latest
      docker login -u AWS -p $(aws ecr get-login-password) https://$(aws sts get-caller-identity --query Account --output text).dkr.ecr.$(aws configure get region).amazonaws.com
      docker push $(aws sts get-caller-identity --query Account --output text).dkr.ecr.$(aws configure get region).amazonaws.com/mythicalmysfits/service:latest
    displayName: 'docker build'
    # env:
    #   AWS_ACCESS_KEY_ID: $(aws_access_key_id)
    #   AWS_SECRET_ACCESS_KEY: $(aws_secret_access_key)
    #   AWS_DEFAULT_REGION: ap-southeast-1