# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dotnet-multienv

variables:
- group: aws

pool:
  vmImage: 'ubuntu-latest'

# steps:
# - script: echo $(aws_access_key_id)
  # displayName: 'npm version'
# - script: node -v
#   displayName: 'node version'
# - script: env && pwd && ls $BUILD_SOURCESDIRECTORY
#   displayName: 'environment variable'
# - script: |
#     cp ./module-1/frontend/src/environments/environment.ts ./module-1/frontend/src/environments/environment.prod.ts
#     sed -i 's/false/true/g' ./module-1/frontend/src/environments/environment.prod.ts
#     npm install 
#   displayName: 'Create a production Angular environment file'

- script: |
    echo [default] | tee ~/.aws/credentials
    echo aws_access_key_id=$(aws_access_key_id) | tee -a ~/.aws/credentials
    echo aws_secret_access_key=$(aws_secret_access_key) | tee -a ~/.aws/credentials
    
    echo [default] | tee ~/.aws/config
    echo region=ap-southeast-1 | tee -a ~/.aws/config
    echo output=json | tee -a ~/.aws/config
  displayName: 'Set AWS credential'

- script: |
    cd $BUILD_SOURCESDIRECTORY"/module-1/frontend"
    npm install 
    cd $BUILD_SOURCESDIRECTORY"/module-1/deploy-frontend-scripts"
    ./deploy_frontend.sh
  displayName: 'npm install'


